services:
  server:
    image: cogram-server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
  worker:
    image: cogram-worker
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
  dummy:
    image: cogram-dummy
    container_name: dummy
    volumes:
      - ./media:/var/media
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: ./Dockerfile.dummy
  redis:
    image: redis
    container_name: cogram-redis
